version: '2'
services:
  pyprflow-workflow:
    image: esscott1/pyprflow:release-0.1.1
    networks:
      pyprflownet:
        ipv4_address: 10.5.0.3
    ports:
      - "5000:5000"
    depends_on:
      - "db"
  db:
    image: "microsoft/mssql-server-linux"
    container_name: db
    networks:
      pyprflownet:
        ipv4_address: 10.5.0.2
    environment:
        SA_PASSWORD: "!!nimda1"
        ACCEPT_EULA: "Y"
 
 networks:
   pyprflownet:
     driver: bridge
      ipam:
        config:
          subnet: 10.5.0.0/16
          gateway: 10.5.0.1
 