steps:
- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'publish', '-c', 'Release', '-o','epublish' ]


- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', './netcore2_2/src/pyprflow.Api/epublish/app.yaml']
  timeout: 600s
