# publish asp.net core solution  
#steps:
-# name: microsoft/dotnet:2.2-sdk
 # args: ['dotnet', 'publish','-c','Release']


steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', './netcore2_2/src/pyprflow.Api/app.yaml']
  timeout: 600s
